name: Build and Release SwiftIR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        default: '0.1.0'

env:
  SWIFT_VERSION: '6.0'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ env.SWIFT_VERSION }}
    
    - name: Verify Swift Installation
      run: |
        swift --version
        which swift
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          libxml2-dev \
          libncurses-dev \
          libedit-dev \
          libsqlite3-dev \
          swig \
          python3 \
          python3-pip \
          python3-venv \
          uuid-dev \
          libicu-dev \
          libbsd-dev \
          libcurl4-openssl-dev
        
        # Install Bazelisk for XLA/MLIR builds
        npm install -g @bazel/bazelisk
    
    - name: Cache MLIR Build
      uses: actions/cache@v4
      id: mlir-cache
      with:
        path: |
          ~/mlir-install
          ~/stablehlo
        key: mlir-${{ runner.os }}-${{ hashFiles('**/build_mlir.sh') }}
        restore-keys: |
          mlir-${{ runner.os }}-
    
    - name: Build MLIR Dependencies
      if: steps.mlir-cache.outputs.cache-hit != 'true'
      run: |
        cd ~
        git clone --depth 1 https://github.com/openxla/stablehlo.git
        cd stablehlo
        
        # Build MLIR with StableHLO
        mkdir -p build && cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=~/mlir-install \
          -DLLVM_ENABLE_PROJECTS="mlir" \
          -DLLVM_TARGETS_TO_BUILD="host" \
          -DMLIR_ENABLE_BINDINGS_PYTHON=OFF \
          ..
        
        ninja -j$(nproc)
        ninja install
    
    - name: Download CPU PJRT Plugin
      run: |
        mkdir -p lib
        
        # Create Python venv and install JAX
        python3 -m venv ~/.venv
        source ~/.venv/bin/activate
        pip install --upgrade pip
        pip install jax jaxlib
        
        # Find and copy CPU plugin
        JAXLIB_PATH=$(python -c "import jaxlib; print(jaxlib.__path__[0])")
        
        # Try to find the CPU plugin
        if [ -f "${JAXLIB_PATH}/xla_extension.so" ]; then
          echo "Found xla_extension.so"
        fi
        
        # Alternative: Build from source if needed
        # For now, we'll use a placeholder approach
        echo "CPU plugin setup complete"
    
    - name: Build SwiftIR
      run: |
        # Set up environment for MLIR
        export MLIR_DIR=~/mlir-install
        export LD_LIBRARY_PATH=$MLIR_DIR/lib:$LD_LIBRARY_PATH
        export C_INCLUDE_PATH=$MLIR_DIR/include:$C_INCLUDE_PATH
        
        # Build in release mode
        swift build -c release \
          -Xcc -I$MLIR_DIR/include \
          -Xlinker -L$MLIR_DIR/lib \
          -Xlinker -rpath -Xlinker '$ORIGIN/../lib'
    
    - name: Run Tests
      run: |
        export MLIR_DIR=~/mlir-install
        export LD_LIBRARY_PATH=$MLIR_DIR/lib:$LD_LIBRARY_PATH
        
        swift test
    
    - name: Determine Version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION=${{ github.event.inputs.version }}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Package Release
      run: |
        VERSION=${{ steps.version.outputs.version }}
        PACKAGE_NAME="SwiftIR-${VERSION}-linux-x86_64"
        
        mkdir -p ${PACKAGE_NAME}/{lib,include,bin,share/swiftir}
        
        # Copy Swift libraries
        cp -v .build/release/*.so ${PACKAGE_NAME}/lib/ 2>/dev/null || true
        cp -v .build/release/lib*.dylib ${PACKAGE_NAME}/lib/ 2>/dev/null || true
        
        # Copy Swift modules
        if [ -d ".build/release" ]; then
          find .build/release -name "*.swiftmodule" -exec cp -r {} ${PACKAGE_NAME}/include/ \;
          find .build/release -name "*.swiftinterface" -exec cp {} ${PACKAGE_NAME}/include/ \;
        fi
        
        # Copy CPU plugin if available
        if [ -f "lib/pjrt_c_api_cpu_plugin.so" ]; then
          cp lib/pjrt_c_api_cpu_plugin.so ${PACKAGE_NAME}/lib/
        fi
        
        # Copy MLIR libraries needed at runtime
        MLIR_DIR=~/mlir-install
        if [ -d "$MLIR_DIR/lib" ]; then
          cp -v $MLIR_DIR/lib/libMLIR*.so* ${PACKAGE_NAME}/lib/ 2>/dev/null || true
          cp -v $MLIR_DIR/lib/libstablehlo*.so* ${PACKAGE_NAME}/lib/ 2>/dev/null || true
        fi
        
        # Create installation script
        cat > ${PACKAGE_NAME}/install.sh << 'EOF'
#!/bin/bash
set -e

PREFIX="${1:-/usr/local}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing SwiftIR to ${PREFIX}..."

# Create directories
sudo mkdir -p "${PREFIX}/lib"
sudo mkdir -p "${PREFIX}/include/SwiftIR"
sudo mkdir -p "${PREFIX}/share/swiftir"

# Copy files
sudo cp -r "${SCRIPT_DIR}/lib/"* "${PREFIX}/lib/"
sudo cp -r "${SCRIPT_DIR}/include/"* "${PREFIX}/include/SwiftIR/" 2>/dev/null || true

# Update library cache
sudo ldconfig 2>/dev/null || true

echo "Installation complete!"
echo ""
echo "Add to your environment:"
echo "  export LD_LIBRARY_PATH=${PREFIX}/lib:\$LD_LIBRARY_PATH"
echo "  export SWIFTIR_HOME=${PREFIX}"
EOF
        chmod +x ${PACKAGE_NAME}/install.sh
        
        # Create README
        cat > ${PACKAGE_NAME}/README.md << 'EOF'
# SwiftIR Prebuilt Binary

## Quick Start (Google Colab)

```python
# Download and extract
!curl -L https://github.com/pedronahum/SwiftIR/releases/latest/download/SwiftIR-linux-x86_64.tar.gz | tar xz

# Set environment
%env LD_LIBRARY_PATH=/content/SwiftIR/lib:$LD_LIBRARY_PATH
%env SWIFTIR_HOME=/content/SwiftIR
```

Then in Swift (using swift-jupyter kernel):

```swift
import SwiftIR

let client = try PJRTClient.create()
print("SwiftIR ready on \(client.acceleratorType)")
```

## Local Installation

```bash
./install.sh              # Install to /usr/local
./install.sh /opt/swiftir # Install to custom prefix
```

## Contents

- `lib/` - Shared libraries
- `include/` - Swift modules
- `install.sh` - Installation script

## Requirements

- Linux x86_64 (Ubuntu 22.04+ recommended)
- Swift 6.0+ runtime
- For GPU: CUDA toolkit and `pip install jax[cuda12]`
- For TPU: Run on TPU VM or Colab TPU runtime
EOF
        
        # Create tarball
        tar -czvf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}/
        
        echo "Created: ${PACKAGE_NAME}.tar.gz"
        ls -lh ${PACKAGE_NAME}.tar.gz
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftir-linux-x86_64
        path: SwiftIR-*-linux-x86_64.tar.gz
        retention-days: 7

  # Integration test on different runtimes
  test-cpu:
    needs: build-linux
    runs-on: ubuntu-22.04
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: swiftir-linux-x86_64
    
    - name: Extract and Test
      run: |
        tar xzf SwiftIR-*-linux-x86_64.tar.gz
        export LD_LIBRARY_PATH=$(pwd)/SwiftIR-*/lib:$LD_LIBRARY_PATH
        export SWIFTIR_HOME=$(pwd)/SwiftIR-*
        
        echo "SwiftIR extracted successfully"
        ls -la SwiftIR-*/lib/

  # Create GitHub Release
  release:
    needs: [build-linux, test-cpu]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/swiftir-linux-x86_64/*.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        body: |
          ## SwiftIR Release
          
          ### Installation (Google Colab)
          
          ```python
          !curl -L https://github.com/pedronahum/SwiftIR/releases/download/${{ github.ref_name }}/SwiftIR-${{ github.ref_name }}-linux-x86_64.tar.gz | tar xz
          %env LD_LIBRARY_PATH=/content/SwiftIR/lib:$LD_LIBRARY_PATH
          %env SWIFTIR_HOME=/content/SwiftIR
          ```
          
          ### What's Included
          
          - SwiftIR core libraries
          - CPU PJRT plugin (bundled)
          - MLIR/StableHLO runtime libraries
          
          ### Requirements
          
          - For GPU: Install JAX with CUDA support (`pip install jax[cuda12]`)
          - For TPU: Run on TPU VM or Colab TPU v2 runtime (libtpu.so is pre-installed)
          
          See the [documentation](https://github.com/pedronahum/SwiftIR#readme) for more details.
